deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: portfolio-server
  env: ''
  on:
    branch: master
    repo: timkellogg/portfolio-server
services:
  - postgresql
before_script:
  - psql -c 'create database portfolio-server_production;' -U postgres -P $PORTFOLIO-SERVER_DATABASE_PASSWORD
  - bundle exec rails db:create && bundle exec rails db:migrate
  